### ISSUE TITLE
[LAVASUIT]

### ISSUE THREAD

**Issue by CodAldo** [MT-Eurythmia/Eurythmia-website#4]
Un problème survient régulièrement avec la lava suit
Lorsque les joueur vont dans la lave avec une lava suit neuf il y a des chances que celui-ci prenne des dégâts tandis que la suit elle perd de la durabilité
Serais-es un problème de synchronisation de l'inventaire du client et le server?

**Comment by paly2** [comment]
Salut, c'est corrigé : https://github.com/MT-Eurythmia/Eurythmia-Evolution/commit/ea921a2c04b3ca0d55cd217234cbda5c63647766 et https://github.com/MT-Eurythmia/Eurythmia-Evolution/commit/64f994da3aac825fe125dec9397037efb1622eaa.

Les lavasuit entraient en conflit avec 3d_armor. Au prochain reboot, il n'y aura plus de lavasuit, à la place, il y aura un bouclier ("Lava Shield") à mettre dans l'armure qui protège de la lave exactement comme la lavasuit. Le bouclier pourra être crafté en combinant un bouclier de crystal avec un saut de lave.
Pour la prochaine fois : cette issue n'est pas bien placée. Ce dépôt est celui du side Web, il aurait fallu la mettre sur le dépôt du serveur Minetest : https://github.com/MT-Eurythmia/Eurythmia-Evolution.
